services:
  - type: web
    name: video-mind-pro
    env: python
    buildCommand: ""
    startCommand: ./start.sh
    plan: free
    envVars:
      - key: GEMINI_API_KEY
        value: YOUR_API_KEY_AQUI
